FROM maven:3.8.6-openjdk-18 AS build
ADD pom.xml /app/
WORKDIR /app/
RUN ["mvn", "dependency:go-offline"]
ADD src /app/src/
RUN ["mvn", "install", "-Pdocker"]

FROM quay.io/wildfly/wildfly:27.0.0.Final-jdk17
COPY --from=build /app/target/Dac-Atividade-Av-01-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/
RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#1111 --silent
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]